<!-- Começa Aqui -->
<script language="JavaScript">
function protegercodigo() {
if (event.button==2||event.button==3) {
alert('Para solicitar algum Script entre en contato comercial@comercialweb.com.br              Shop Quality - (2000) - Todos os direitos reservados.!');}
}
document.onmousedown=protegercodigo
</script>
        <!-------- Termina Aqui --------> 
<hr>
<font color="#000000" size="1" face="Arial, Helvetica, sans-serif"> </font> 
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
      
    <td width="8%"><a href="javascript:top.close(self);" ('fechar','','../imagens/fechar2.jpg',1)"><img src="file:///C|/informatica/loja_script/imagem/fechar.gif" width="90" height="20" border="0"></a></td>
      
    <td width="92%"> 
      <div align="center"><font color="#000000" size="1" face="Arial, Helvetica, sans-serif">Desenvolvimento 
          de Script&acute;s sob encomenda Loja virtual , Mural , Autentica&ccedil;&atilde;o 
          , Bate Papo , Forum<br>
          Cadastro de clientes , Contadores entre outros...<br>
          Desenvolvido por: <a href="http://www.comercialweb.com.br" target="_blank"> 
          Comercialweb</a></font> <font color="#000000" size="1" face="Arial, Helvetica, sans-serif">Desenvolvimentos 
          e Hospedagem<br>
          E-mail: <a href="mailto:comercial@comercialweb.com.br">comercial@comercialweb.com.br</a> 
          </font> <font face="Arial, Helvetica, sans-serif" size="1" color="#000000"> 
          ou <a href="mailto:yy200@ig.com.br">yy200@ig.com.br</a> </font></div>
      </td>
    </tr>
  </table>


